# Generated by Django 4.0.4 on 2022-05-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('description', models.TextField(default='')),
                ('sex', models.BooleanField(null=True)),
                ('grade', models.IntegerField(null=True)),
                ('major', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('blockTime', models.IntegerField(default=0)),
                ('first_login', models.BooleanField(default=True)),
                ('security_issue', models.CharField(default='密保问题', max_length=255)),
                ('security_answer', models.CharField(default='密保答案', max_length=255)),
            ],
        ),
    ]
